# Generated by Django 3.0.6 on 2020-05-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('S', 'Shirt'), ('C', 'chaussures'), ('A', 'accessoires')], max_length=1)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(max_length=48)),
                ('etat', models.CharField(blank=True, choices=[('N', 'nouveau'), ('R', 'rupture'), ('P', 'promotion')], default='N', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(default=0)),
                ('nom_du_client', models.CharField(max_length=40)),
                ('prenom_du_client', models.CharField(max_length=40)),
                ('adresse_du_client', models.CharField(max_length=40)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('confirmer', models.BooleanField(default=False)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Commune')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Produit')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Wilaya')),
            ],
        ),
    ]
