# Generated by Django 3.0.6 on 2020-05-10 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='date_updated',
            new_name='date_added',
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_client', models.CharField(max_length=40)),
                ('prenom_du_client', models.CharField(max_length=40)),
                ('adresse_du_client', models.CharField(max_length=40)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Produit')),
            ],
        ),
    ]
