# Generated by Django 3.0.6 on 2020-05-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200527_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cout_livraison',
            field=models.CharField(choices=[('AL', '400'), ('AU', '600')], default='AU', max_length=2),
        ),
        migrations.AddField(
            model_name='checkout',
            name='montant_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='etat',
            field=models.CharField(choices=[('N', 'nouveau'), ('R', 'rupture'), ('P', 'promotion')], default='N', max_length=1),
        ),
    ]
