# Generated by Django 3.0.6 on 2020-05-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200531_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cout_livraison',
            field=models.CharField(choices=[('AL', 'alger'), ('AU', 'autres')], default='AU', max_length=2),
        ),
    ]
