# Generated by Django 3.0.6 on 2020-05-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200510_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('C', 'chaussures'), ('A', 'accessoires')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='prix',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='price',
            field=models.IntegerField(),
        ),
    ]
