# Generated by Django 3.0.6 on 2020-05-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200531_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cout_livraison',
            field=models.IntegerField(choices=[('AL', 'alger'), ('AU', 'autres')], default='AU', max_length=2),
        ),
    ]
