# Generated by Django 3.0.6 on 2020-05-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200518_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='label',
        ),
        migrations.AddField(
            model_name='produit',
            name='etat',
            field=models.CharField(blank=True, choices=[('N', 'nouveau'), ('R', 'rupture'), ('P', 'promotion')], default='N', max_length=1),
        ),
    ]
