# Generated by Django 3.0.6 on 2020-06-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200531_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(default=0)),
                ('nom_du_client', models.CharField(max_length=40)),
                ('prenom_du_client', models.CharField(max_length=40)),
                ('adresse_du_client', models.CharField(max_length=40)),
                ('cout_livraison', models.IntegerField(choices=[(400, 'alger'), (600, 'autres')], default=600)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('confirmer', models.BooleanField(default=False)),
                ('montant_total', models.IntegerField(default=0)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Commune')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Produit')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Wilaya')),
            ],
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
