# Generated by Django 3.0.6 on 2020-05-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200520_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='country',
            new_name='Wilaya',
        ),
    ]
