# Generated by Django 3.0.6 on 2020-05-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200520_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Commune'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Wilaya'),
        ),
    ]
