# Generated by Django 3.0.6 on 2020-06-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200601_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
