# Generated by Django 3.0.6 on 2020-06-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200601_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adresse_du_client',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cout_livraison',
            new_name='livraison',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='nom_du_client',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='prenom_du_client',
            new_name='prenom',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='montant_total',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='in_stock',
        ),
    ]
