# Generated by Django 3.0.6 on 2020-06-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200603_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='livraison',
            field=models.IntegerField(default=600),
        ),
    ]
